# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/flipbook_UI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!
import os
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 650)
        MainWindow.setMinimumSize(QtCore.QSize(913, 631))
        MainWindow.setMaximumSize(QtCore.QSize(913, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_18.addWidget(self.line, 0, 1, 4, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(320, 121))
        self.frame_2.setMaximumSize(QtCore.QSize(320, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.l_logo = QtWidgets.QLabel(self.frame_2)
        self.l_logo.setMinimumSize(QtCore.QSize(320, 121))
        self.l_logo.setMaximumSize(QtCore.QSize(320, 110))
        self.l_logo.setText("")
        self.l_logo.setPixmap(QtGui.QPixmap(os.path.abspath(os.path.curdir + "/logo/logo2.png")))
        self.l_logo.setScaledContents(True)
        self.l_logo.setObjectName("l_logo")
        self.gridLayout_25.addWidget(self.l_logo, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_2, 0, 0, 1, 1)
        self.fr_preview = QtWidgets.QFrame(self.centralwidget)
        self.fr_preview.setMinimumSize(QtCore.QSize(542, 593))
        self.fr_preview.setMaximumSize(QtCore.QSize(542, 593))
        self.fr_preview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_preview.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_preview.setObjectName("fr_preview")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fr_preview)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.grb_preview = QtWidgets.QGroupBox(self.fr_preview)
        self.grb_preview.setMinimumSize(QtCore.QSize(542, 600))
        self.grb_preview.setMaximumSize(QtCore.QSize(542, 600))
        self.grb_preview.setObjectName("grb_preview")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grb_preview)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fr_preview_image = QtWidgets.QFrame(self.grb_preview)
        self.fr_preview_image.setMinimumSize(QtCore.QSize(512, 512))
        self.fr_preview_image.setMaximumSize(QtCore.QSize(512, 512))
        self.fr_preview_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_preview_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_preview_image.setObjectName("fr_preview_image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fr_preview_image)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.l_preview_image = QtWidgets.QLabel(self.fr_preview_image)
        self.l_preview_image.setMaximumSize(QtCore.QSize(512, 512))
        self.l_preview_image.setStyleSheet("background-color: rgb(89, 90, 90);\n"
"border-radius: 10px;")
        self.l_preview_image.setText("")
        self.l_preview_image.setAlignment(QtCore.Qt.AlignCenter)
        self.l_preview_image.setObjectName("l_preview_image")
        self.gridLayout_3.addWidget(self.l_preview_image, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.fr_preview_image, 0, 0, 1, 1)
        self.fr_frame_slider = QtWidgets.QFrame(self.grb_preview)
        self.fr_frame_slider.setMinimumSize(QtCore.QSize(512, 30))
        self.fr_frame_slider.setMaximumSize(QtCore.QSize(512, 30))
        self.fr_frame_slider.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_frame_slider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_frame_slider.setObjectName("fr_frame_slider")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.fr_frame_slider)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.sl_frame = QtWidgets.QSlider(self.fr_frame_slider)
        self.sl_frame.setMinimumSize(QtCore.QSize(512, 30))
        self.sl_frame.setMaximumSize(QtCore.QSize(512, 30))
        self.sl_frame.setOrientation(QtCore.Qt.Horizontal)
        self.sl_frame.setInvertedAppearance(False)
        self.sl_frame.setInvertedControls(False)
        self.sl_frame.setObjectName("sl_frame")
        self.gridLayout_14.addWidget(self.sl_frame, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.fr_frame_slider, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.grb_preview, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.fr_preview, 0, 2, 4, 1)
        self.grb_subuv_image = QtWidgets.QGroupBox(self.centralwidget)
        self.grb_subuv_image.setMinimumSize(QtCore.QSize(320, 76))
        self.grb_subuv_image.setMaximumSize(QtCore.QSize(320, 76))
        self.grb_subuv_image.setObjectName("grb_subuv_image")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.grb_subuv_image)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fr_select_field = QtWidgets.QFrame(self.grb_subuv_image)
        self.fr_select_field.setMinimumSize(QtCore.QSize(275, 25))
        self.fr_select_field.setMaximumSize(QtCore.QSize(275, 25))
        self.fr_select_field.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_select_field.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_select_field.setObjectName("fr_select_field")
        self.gridLayout = QtWidgets.QGridLayout(self.fr_select_field)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fld_path = QtWidgets.QLineEdit(self.fr_select_field)
        self.fld_path.setMinimumSize(QtCore.QSize(248, 25))
        self.fld_path.setMaximumSize(QtCore.QSize(248, 25))
        self.fld_path.setAlignment(QtCore.Qt.AlignCenter)
        self.fld_path.setObjectName("fld_path")
        self.gridLayout.addWidget(self.fld_path, 0, 0, 1, 1)
        self.btn_path = QtWidgets.QToolButton(self.fr_select_field)
        self.btn_path.setMinimumSize(QtCore.QSize(28, 25))
        self.btn_path.setMaximumSize(QtCore.QSize(28, 25))
        self.btn_path.setObjectName("btn_path")
        self.gridLayout.addWidget(self.btn_path, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.fr_select_field, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.grb_subuv_image, 1, 0, 1, 1)
        self.grb_output = QtWidgets.QGroupBox(self.centralwidget)
        self.grb_output.setMinimumSize(QtCore.QSize(320, 180))
        self.grb_output.setMaximumSize(QtCore.QSize(320, 180))
        self.grb_output.setObjectName("grb_output")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.grb_output)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.fr_outpath = QtWidgets.QFrame(self.grb_output)
        self.fr_outpath.setMinimumSize(QtCore.QSize(275, 25))
        self.fr_outpath.setMaximumSize(QtCore.QSize(275, 25))
        self.fr_outpath.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_outpath.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_outpath.setObjectName("fr_outpath")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.fr_outpath)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.fld_out_path = QtWidgets.QLineEdit(self.fr_outpath)
        self.fld_out_path.setMinimumSize(QtCore.QSize(248, 25))
        self.fld_out_path.setMaximumSize(QtCore.QSize(248, 25))
        self.fld_out_path.setAlignment(QtCore.Qt.AlignCenter)
        self.fld_out_path.setObjectName("fld_out_path")
        self.gridLayout_24.addWidget(self.fld_out_path, 0, 0, 1, 1)
        self.btn_out_path = QtWidgets.QToolButton(self.fr_outpath)
        self.btn_out_path.setMinimumSize(QtCore.QSize(28, 25))
        self.btn_out_path.setMaximumSize(QtCore.QSize(28, 25))
        self.btn_out_path.setObjectName("btn_out_path")
        self.gridLayout_24.addWidget(self.btn_out_path, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.fr_outpath, 0, 0, 1, 1)
        self.fr_save_butons_2 = QtWidgets.QFrame(self.grb_output)
        self.fr_save_butons_2.setMinimumSize(QtCore.QSize(280, 61))
        self.fr_save_butons_2.setMaximumSize(QtCore.QSize(280, 61))
        self.fr_save_butons_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_save_butons_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_save_butons_2.setObjectName("fr_save_butons_2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.fr_save_butons_2)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.fr_range_main = QtWidgets.QFrame(self.fr_save_butons_2)
        self.fr_range_main.setMinimumSize(QtCore.QSize(151, 61))
        self.fr_range_main.setMaximumSize(QtCore.QSize(151, 61))
        self.fr_range_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_range_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_range_main.setObjectName("fr_range_main")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.fr_range_main)
        self.gridLayout_21.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.fr_range_l = QtWidgets.QFrame(self.fr_range_main)
        self.fr_range_l.setMinimumSize(QtCore.QSize(50, 61))
        self.fr_range_l.setMaximumSize(QtCore.QSize(50, 61))
        self.fr_range_l.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_range_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_range_l.setObjectName("fr_range_l")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.fr_range_l)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.l_range = QtWidgets.QLabel(self.fr_range_l)
        self.l_range.setMinimumSize(QtCore.QSize(50, 25))
        self.l_range.setMaximumSize(QtCore.QSize(50, 25))
        self.l_range.setObjectName("l_range")
        self.gridLayout_19.addWidget(self.l_range, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.fr_range_l, 0, 0, 1, 1)
        self.fr_range_divide_lines = QtWidgets.QFrame(self.fr_range_main)
        self.fr_range_divide_lines.setMinimumSize(QtCore.QSize(41, 61))
        self.fr_range_divide_lines.setMaximumSize(QtCore.QSize(41, 61))
        self.fr_range_divide_lines.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_range_divide_lines.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_range_divide_lines.setObjectName("fr_range_divide_lines")
        self.top_line = QtWidgets.QFrame(self.fr_range_divide_lines)
        self.top_line.setGeometry(QtCore.QRect(10, 0, 20, 20))
        self.top_line.setMinimumSize(QtCore.QSize(20, 20))
        self.top_line.setMaximumSize(QtCore.QSize(20, 20))
        self.top_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.top_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_line.setObjectName("top_line")
        self.bot_line = QtWidgets.QFrame(self.fr_range_divide_lines)
        self.bot_line.setGeometry(QtCore.QRect(10, 40, 20, 20))
        self.bot_line.setMinimumSize(QtCore.QSize(20, 20))
        self.bot_line.setMaximumSize(QtCore.QSize(20, 20))
        self.bot_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bot_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.bot_line.setObjectName("bot_line")
        self.left_line = QtWidgets.QFrame(self.fr_range_divide_lines)
        self.left_line.setGeometry(QtCore.QRect(0, 10, 20, 41))
        self.left_line.setMinimumSize(QtCore.QSize(20, 41))
        self.left_line.setMaximumSize(QtCore.QSize(20, 41))
        self.left_line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.left_line.setObjectName("left_line")
        self.gridLayout_21.addWidget(self.fr_range_divide_lines, 0, 1, 1, 1)
        self.fr_slider_boxes = QtWidgets.QFrame(self.fr_range_main)
        self.fr_slider_boxes.setMinimumSize(QtCore.QSize(50, 61))
        self.fr_slider_boxes.setMaximumSize(QtCore.QSize(50, 61))
        self.fr_slider_boxes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_slider_boxes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_slider_boxes.setObjectName("fr_slider_boxes")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.fr_slider_boxes)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.sb_range_vertical = QtWidgets.QSpinBox(self.fr_slider_boxes)
        self.sb_range_vertical.setMinimumSize(QtCore.QSize(50, 24))
        self.sb_range_vertical.setMaximumSize(QtCore.QSize(50, 24))
        self.sb_range_vertical.setMinimum(1)
        self.sb_range_vertical.setObjectName("sb_range_vertical")
        self.gridLayout_20.addWidget(self.sb_range_vertical, 1, 0, 1, 1)
        self.sb_range_horizontal = QtWidgets.QSpinBox(self.fr_slider_boxes)
        self.sb_range_horizontal.setMinimumSize(QtCore.QSize(50, 24))
        self.sb_range_horizontal.setMaximumSize(QtCore.QSize(50, 24))
        self.sb_range_horizontal.setMinimum(1)
        self.sb_range_horizontal.setObjectName("sb_range_horizontal")
        self.gridLayout_20.addWidget(self.sb_range_horizontal, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.fr_slider_boxes, 0, 2, 1, 1)
        self.gridLayout_22.addWidget(self.fr_range_main, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.fr_save_butons_2)
        self.frame.setMinimumSize(QtCore.QSize(125, 61))
        self.frame.setMaximumSize(QtCore.QSize(125, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_23.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.l_image_format = QtWidgets.QLabel(self.frame)
        self.l_image_format.setMinimumSize(QtCore.QSize(50, 25))
        self.l_image_format.setMaximumSize(QtCore.QSize(50, 25))
        self.l_image_format.setObjectName("l_image_format")
        self.gridLayout_23.addWidget(self.l_image_format, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(75, 26))
        self.comboBox.setMaximumSize(QtCore.QSize(75, 26))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_23.addWidget(self.comboBox, 0, 1, 1, 1)
        self.gridLayout_22.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.fr_save_butons_2, 1, 0, 1, 1)
        self.fr_save_butons = QtWidgets.QFrame(self.grb_output)
        self.fr_save_butons.setMinimumSize(QtCore.QSize(275, 22))
        self.fr_save_butons.setMaximumSize(QtCore.QSize(275, 23))
        self.fr_save_butons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_save_butons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_save_butons.setObjectName("fr_save_butons")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.fr_save_butons)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.btn_save = QtWidgets.QPushButton(self.fr_save_butons)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 21))
        self.btn_save.setMaximumSize(QtCore.QSize(100, 21))
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_17.addWidget(self.btn_save, 0, 0, 1, 1)
        self.btn_saveall = QtWidgets.QPushButton(self.fr_save_butons)
        self.btn_saveall.setMinimumSize(QtCore.QSize(100, 21))
        self.btn_saveall.setMaximumSize(QtCore.QSize(100, 21))
        self.btn_saveall.setObjectName("btn_saveall")
        self.gridLayout_17.addWidget(self.btn_saveall, 0, 1, 1, 1)
        self.gridLayout_26.addWidget(self.fr_save_butons, 2, 0, 1, 1)
        self.gridLayout_18.addWidget(self.grb_output, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(320, 191))
        self.frame_3.setMaximumSize(QtCore.QSize(320, 191))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setVerticalSpacing(0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.grb_image_info = QtWidgets.QGroupBox(self.frame_3)
        self.grb_image_info.setMinimumSize(QtCore.QSize(170, 191))
        self.grb_image_info.setMaximumSize(QtCore.QSize(170, 191))
        self.grb_image_info.setObjectName("grb_image_info")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.grb_image_info)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 20)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.fr_image_info = QtWidgets.QFrame(self.grb_image_info)
        self.fr_image_info.setMinimumSize(QtCore.QSize(150, 150))
        self.fr_image_info.setMaximumSize(QtCore.QSize(150, 125))
        self.fr_image_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_image_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_image_info.setObjectName("fr_image_info")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.fr_image_info)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.fr_size_px = QtWidgets.QFrame(self.fr_image_info)
        self.fr_size_px.setMinimumSize(QtCore.QSize(150, 25))
        self.fr_size_px.setMaximumSize(QtCore.QSize(150, 25))
        self.fr_size_px.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_size_px.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_size_px.setObjectName("fr_size_px")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.fr_size_px)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.l_size_px = QtWidgets.QLabel(self.fr_size_px)
        self.l_size_px.setMinimumSize(QtCore.QSize(60, 25))
        self.l_size_px.setMaximumSize(QtCore.QSize(60, 25))
        self.l_size_px.setObjectName("l_size_px")
        self.gridLayout_7.addWidget(self.l_size_px, 0, 0, 1, 1)
        self.l_t_size_px = QtWidgets.QLabel(self.fr_size_px)
        self.l_t_size_px.setMinimumSize(QtCore.QSize(80, 25))
        self.l_t_size_px.setMaximumSize(QtCore.QSize(80, 25))
        self.l_t_size_px.setText("")
        self.l_t_size_px.setObjectName("l_t_size_px")
        self.gridLayout_7.addWidget(self.l_t_size_px, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.fr_size_px, 3, 0, 1, 1)
        self.fr_format = QtWidgets.QFrame(self.fr_image_info)
        self.fr_format.setMinimumSize(QtCore.QSize(150, 25))
        self.fr_format.setMaximumSize(QtCore.QSize(150, 25))
        self.fr_format.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_format.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_format.setObjectName("fr_format")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.fr_format)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.l_format = QtWidgets.QLabel(self.fr_format)
        self.l_format.setMinimumSize(QtCore.QSize(60, 25))
        self.l_format.setMaximumSize(QtCore.QSize(60, 25))
        self.l_format.setObjectName("l_format")
        self.gridLayout_9.addWidget(self.l_format, 0, 0, 1, 1)
        self.l_t_format = QtWidgets.QLabel(self.fr_format)
        self.l_t_format.setMinimumSize(QtCore.QSize(80, 25))
        self.l_t_format.setMaximumSize(QtCore.QSize(80, 25))
        self.l_t_format.setText("")
        self.l_t_format.setObjectName("l_t_format")
        self.gridLayout_9.addWidget(self.l_t_format, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.fr_format, 1, 0, 1, 1)
        self.fr_mode = QtWidgets.QFrame(self.fr_image_info)
        self.fr_mode.setMinimumSize(QtCore.QSize(150, 25))
        self.fr_mode.setMaximumSize(QtCore.QSize(150, 25))
        self.fr_mode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_mode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_mode.setObjectName("fr_mode")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.fr_mode)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.l_mode = QtWidgets.QLabel(self.fr_mode)
        self.l_mode.setMinimumSize(QtCore.QSize(60, 25))
        self.l_mode.setMaximumSize(QtCore.QSize(60, 25))
        self.l_mode.setObjectName("l_mode")
        self.gridLayout_10.addWidget(self.l_mode, 0, 0, 1, 1)
        self.l_t_mode = QtWidgets.QLabel(self.fr_mode)
        self.l_t_mode.setMinimumSize(QtCore.QSize(80, 25))
        self.l_t_mode.setMaximumSize(QtCore.QSize(80, 25))
        self.l_t_mode.setText("")
        self.l_t_mode.setObjectName("l_t_mode")
        self.gridLayout_10.addWidget(self.l_t_mode, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.fr_mode, 2, 0, 1, 1)
        self.fr_size_mb = QtWidgets.QFrame(self.fr_image_info)
        self.fr_size_mb.setMinimumSize(QtCore.QSize(150, 25))
        self.fr_size_mb.setMaximumSize(QtCore.QSize(150, 25))
        self.fr_size_mb.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_size_mb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_size_mb.setObjectName("fr_size_mb")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.fr_size_mb)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.l_size_mb = QtWidgets.QLabel(self.fr_size_mb)
        self.l_size_mb.setMinimumSize(QtCore.QSize(60, 25))
        self.l_size_mb.setMaximumSize(QtCore.QSize(60, 25))
        self.l_size_mb.setObjectName("l_size_mb")
        self.gridLayout_6.addWidget(self.l_size_mb, 0, 0, 1, 1)
        self.l_t_size_mb = QtWidgets.QLabel(self.fr_size_mb)
        self.l_t_size_mb.setMinimumSize(QtCore.QSize(80, 25))
        self.l_t_size_mb.setMaximumSize(QtCore.QSize(80, 25))
        self.l_t_size_mb.setText("")
        self.l_t_size_mb.setObjectName("l_t_size_mb")
        self.gridLayout_6.addWidget(self.l_t_size_mb, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.fr_size_mb, 4, 0, 1, 1)
        self.fr_name = QtWidgets.QFrame(self.fr_image_info)
        self.fr_name.setMinimumSize(QtCore.QSize(150, 25))
        self.fr_name.setMaximumSize(QtCore.QSize(150, 25))
        self.fr_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_name.setObjectName("fr_name")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.fr_name)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.l_name = QtWidgets.QLabel(self.fr_name)
        self.l_name.setMinimumSize(QtCore.QSize(60, 25))
        self.l_name.setMaximumSize(QtCore.QSize(60, 25))
        self.l_name.setObjectName("l_name")
        self.gridLayout_8.addWidget(self.l_name, 0, 0, 1, 1)
        self.l_t_name = QtWidgets.QLabel(self.fr_name)
        self.l_t_name.setMinimumSize(QtCore.QSize(80, 25))
        self.l_t_name.setMaximumSize(QtCore.QSize(80, 25))
        self.l_t_name.setText("")
        self.l_t_name.setObjectName("l_t_name")
        self.gridLayout_8.addWidget(self.l_t_name, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.fr_name, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.fr_image_info, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.grb_image_info, 0, 0, 2, 1)
        self.grb_frames_count = QtWidgets.QGroupBox(self.frame_3)
        self.grb_frames_count.setMinimumSize(QtCore.QSize(145, 80))
        self.grb_frames_count.setMaximumSize(QtCore.QSize(145, 80))
        self.grb_frames_count.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grb_frames_count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grb_frames_count.setObjectName("grb_frames_count")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.grb_frames_count)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.fr_vertical_line = QtWidgets.QFrame(self.grb_frames_count)
        self.fr_vertical_line.setMinimumSize(QtCore.QSize(120, 25))
        self.fr_vertical_line.setMaximumSize(QtCore.QSize(81, 25))
        self.fr_vertical_line.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_vertical_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_vertical_line.setObjectName("fr_vertical_line")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.fr_vertical_line)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.l_vertical_line = QtWidgets.QLabel(self.fr_vertical_line)
        self.l_vertical_line.setMinimumSize(QtCore.QSize(70, 25))
        self.l_vertical_line.setMaximumSize(QtCore.QSize(70, 25))
        self.l_vertical_line.setObjectName("l_vertical_line")
        self.gridLayout_16.addWidget(self.l_vertical_line, 0, 0, 1, 1)
        self.sb_vertical_line = QtWidgets.QSpinBox(self.fr_vertical_line)
        self.sb_vertical_line.setMinimumSize(QtCore.QSize(50, 24))
        self.sb_vertical_line.setMaximumSize(QtCore.QSize(50, 24))
        self.sb_vertical_line.setMinimum(1)
        self.sb_vertical_line.setObjectName("sb_vertical_line")
        self.gridLayout_16.addWidget(self.sb_vertical_line, 0, 1, 1, 1)
        self.gridLayout_27.addWidget(self.fr_vertical_line, 0, 0, 1, 1)
        self.fr_horizontal_line = QtWidgets.QFrame(self.grb_frames_count)
        self.fr_horizontal_line.setMinimumSize(QtCore.QSize(120, 25))
        self.fr_horizontal_line.setMaximumSize(QtCore.QSize(81, 25))
        self.fr_horizontal_line.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_horizontal_line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_horizontal_line.setObjectName("fr_horizontal_line")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.fr_horizontal_line)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.l_vertical_count = QtWidgets.QLabel(self.fr_horizontal_line)
        self.l_vertical_count.setMinimumSize(QtCore.QSize(70, 25))
        self.l_vertical_count.setMaximumSize(QtCore.QSize(70, 25))
        self.l_vertical_count.setObjectName("l_vertical_count")
        self.gridLayout_15.addWidget(self.l_vertical_count, 0, 0, 1, 1)
        self.sb_horizontal_line = QtWidgets.QSpinBox(self.fr_horizontal_line)
        self.sb_horizontal_line.setMinimumSize(QtCore.QSize(50, 24))
        self.sb_horizontal_line.setMaximumSize(QtCore.QSize(50, 24))
        self.sb_horizontal_line.setMinimum(1)
        self.sb_horizontal_line.setObjectName("sb_horizontal_line")
        self.gridLayout_15.addWidget(self.sb_horizontal_line, 0, 1, 1, 1)
        self.gridLayout_27.addWidget(self.fr_horizontal_line, 1, 0, 1, 1)
        self.gridLayout_30.addWidget(self.grb_frames_count, 0, 1, 1, 1)
        self.grb_frames_count_2 = QtWidgets.QGroupBox(self.frame_3)
        self.grb_frames_count_2.setMinimumSize(QtCore.QSize(145, 110))
        self.grb_frames_count_2.setMaximumSize(QtCore.QSize(145, 110))
        self.grb_frames_count_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grb_frames_count_2.setObjectName("grb_frames_count_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.grb_frames_count_2)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setSpacing(0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.fr_vertical_line_2 = QtWidgets.QFrame(self.grb_frames_count_2)
        self.fr_vertical_line_2.setMinimumSize(QtCore.QSize(140, 25))
        self.fr_vertical_line_2.setMaximumSize(QtCore.QSize(140, 25))
        self.fr_vertical_line_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_vertical_line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_vertical_line_2.setObjectName("fr_vertical_line_2")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.fr_vertical_line_2)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.l_vertical_line_2 = QtWidgets.QLabel(self.fr_vertical_line_2)
        self.l_vertical_line_2.setMinimumSize(QtCore.QSize(55, 25))
        self.l_vertical_line_2.setMaximumSize(QtCore.QSize(55, 25))
        self.l_vertical_line_2.setObjectName("l_vertical_line_2")
        self.gridLayout_29.addWidget(self.l_vertical_line_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.fr_vertical_line_2)
        self.label.setMinimumSize(QtCore.QSize(80, 25))
        self.label.setMaximumSize(QtCore.QSize(80, 25))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_29.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.fr_vertical_line_2, 2, 1, 1, 1)
        self.fr_vertical_line_3 = QtWidgets.QFrame(self.grb_frames_count_2)
        self.fr_vertical_line_3.setMinimumSize(QtCore.QSize(140, 25))
        self.fr_vertical_line_3.setMaximumSize(QtCore.QSize(140, 25))
        self.fr_vertical_line_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_vertical_line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_vertical_line_3.setObjectName("fr_vertical_line_3")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.fr_vertical_line_3)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setSpacing(0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.l_vertical_line_3 = QtWidgets.QLabel(self.fr_vertical_line_3)
        self.l_vertical_line_3.setMinimumSize(QtCore.QSize(55, 25))
        self.l_vertical_line_3.setMaximumSize(QtCore.QSize(55, 25))
        self.l_vertical_line_3.setObjectName("l_vertical_line_3")
        self.gridLayout_31.addWidget(self.l_vertical_line_3, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fr_vertical_line_3)
        self.label_3.setMinimumSize(QtCore.QSize(80, 25))
        self.label_3.setMaximumSize(QtCore.QSize(80, 25))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_31.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.fr_vertical_line_3, 3, 1, 1, 1)
        self.fr_horizontal_line_2 = QtWidgets.QFrame(self.grb_frames_count_2)
        self.fr_horizontal_line_2.setMinimumSize(QtCore.QSize(140, 25))
        self.fr_horizontal_line_2.setMaximumSize(QtCore.QSize(140, 25))
        self.fr_horizontal_line_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_horizontal_line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_horizontal_line_2.setObjectName("fr_horizontal_line_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.fr_horizontal_line_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.l_vertical_count_2 = QtWidgets.QLabel(self.fr_horizontal_line_2)
        self.l_vertical_count_2.setMinimumSize(QtCore.QSize(55, 25))
        self.l_vertical_count_2.setMaximumSize(QtCore.QSize(55, 25))
        self.l_vertical_count_2.setObjectName("l_vertical_count_2")
        self.gridLayout_13.addWidget(self.l_vertical_count_2, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.fr_horizontal_line_2)
        self.label_2.setMinimumSize(QtCore.QSize(80, 25))
        self.label_2.setMaximumSize(QtCore.QSize(80, 25))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_28.addWidget(self.fr_horizontal_line_2, 0, 1, 1, 1)
        self.gridLayout_30.addWidget(self.grb_frames_count_2, 1, 1, 1, 1)
        self.gridLayout_18.addWidget(self.frame_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.sl_frame.valueChanged['int'].connect(self.sb_range_vertical.setValue)
        self.sl_frame.valueChanged['int'].connect(self.sb_range_horizontal.setValue)
        self.sl_frame.valueChanged['int'].connect(self.label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlipBook Converter"))
        self.grb_preview.setTitle(_translate("MainWindow", "Preview"))
        self.grb_subuv_image.setTitle(_translate("MainWindow", "SubUV image"))
        self.fld_path.setPlaceholderText(_translate("MainWindow", "Image Path"))
        self.btn_path.setText(_translate("MainWindow", "..."))
        self.grb_output.setTitle(_translate("MainWindow", "Output"))
        self.fld_out_path.setPlaceholderText(_translate("MainWindow", "Output Path"))
        self.btn_out_path.setText(_translate("MainWindow", "..."))
        self.l_range.setText(_translate("MainWindow", "Range:"))
        self.l_image_format.setText(_translate("MainWindow", "Format:"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_saveall.setText(_translate("MainWindow", "SaveAll"))
        self.grb_image_info.setTitle(_translate("MainWindow", "Image info"))
        self.l_size_px.setText(_translate("MainWindow", "Size(px):"))
        self.l_format.setText(_translate("MainWindow", "Format:"))
        self.l_mode.setText(_translate("MainWindow", "Mode:"))
        self.l_size_mb.setText(_translate("MainWindow", "Size(Mb):"))
        self.l_name.setText(_translate("MainWindow", "Name:"))
        self.grb_frames_count.setTitle(_translate("MainWindow", "Frame lines"))
        self.l_vertical_line.setText(_translate("MainWindow", "Vertical:"))
        self.l_vertical_count.setText(_translate("MainWindow", "Horizontal:"))
        self.grb_frames_count_2.setTitle(_translate("MainWindow", "Frame stats"))
        self.l_vertical_line_2.setText(_translate("MainWindow", "Current:"))
        self.l_vertical_line_3.setText(_translate("MainWindow", "Size(px):"))
        self.l_vertical_count_2.setText(_translate("MainWindow", "Count:"))

